camera_id: F012_27F_MAT
video_date: 240801
video_num: 1
video_extension: .avi

model: ../models/yolov8m/yolov8m.pt
model_params:
  imgsz: 960
  verbose: false
  conf: 0.05
  iou: 0.4
  classes: [0, 1, 2, 3, 5, 7]
  agnostic_nms: false

coco_class:
  "0": person
  "1": bicycle
  "2": car
  "3": motorcycle
  "5": bus
  "7": truck
category_classes:
  twowheels: [bicycle, motorcycle]
  car: [car]
  heavy: [bus, truck]
category_confidence:
  twowheels: 0.05
  car: 0.6
  heavy: 0.6